title: "Nu Wai Thet (Sophia)"
description: "Data Scientist and ML Engineer specializing in NLP, analytics, and deployment."
url: "https://nuwai.github.io"
baseurl: "/nuwaithet_sophia_portfolio"
author:
  name: "Nu Wai Thet (Sophia)"
  email: "nuwaithet@gmail.com"
  github: "https://github.com/Nuwai"
  linkedin: "https://www.linkedin.com/in/nuwai-thet-sophia/"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
show_excerpts: false
